version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: lilo-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: lilo-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/lilo-assignment?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: lilo-client
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - server
    environment:
      REACT_APP_API_BASE_URL: http://localhost:5000/api

volumes:
  mongodb_data:
